### ISSUE TITLE
v0.0.5-Beta 游戏崩溃 第2关

### ISSUE THREAD

**Issue by IVSpretender** [LingoSuko/UniverseLite#1]
在开局第2小批僵尸出现的时候，游戏崩溃（fatal error），崩溃信息如下：
Exception: Access Violation (code 0xc0000005) at address 004734A6 in thread 1600
Module: PlantsVsZombies.exe
Logical Address: 0001:000724A6

0019FA08 004734A6 0001:000724A6 PlantsVsZombies.exe
Params: 1BC98B10 1BC98B10 0019FA88 1BC98B10

EAX:0AA94A18 EBX:0A933058 ECX:00000CC0 EDX:00000000 ESI:1BF6A1F8 EDI:000000C9
EIP:004734A6 ESP:0019F9CC  EBP:0019FA08
CS:0023 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:00010216

Windows Ver: NT 6.2  Build 9200
DDraw Ver: 
DSound Ver: 

Product: PlantsVsZombies
Version: 1.0.0.1051
Time Loaded: 00:01:32
Fullscreen: 是

**Comment by LingoSuko** [comment]
出现情况频繁吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LingoSuko/UniverseLite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月15日(星期一) 晚上8:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[LingoSuko/UniverseLite] Ver0.0.5 游戏崩溃 第2关 (Issue #1)





 
在开局第2小批僵尸出现的时候，游戏崩溃（fatal error），崩溃信息如下：
 Exception: Access Violation (code 0xc0000005) at address 004734A6 in thread 1600
 Module: PlantsVsZombies.exe
 Logical Address: 0001:000724A6
 
0019FA08 004734A6 0001:000724A6 PlantsVsZombies.exe
 Params: 1BC98B10 1BC98B10 0019FA88 1BC98B10
 
EAX:0AA94A18 EBX:0A933058 ECX:00000CC0 EDX:00000000 ESI:1BF6A1F8 EDI:000000C9
 EIP:004734A6 ESP:0019F9CC  EBP:0019FA08
 CS:0023 SS:002B DS:002B ES:002B FS:0053 GS:002B
 Flags:00010216
 
Windows Ver: NT 6.2  Build 9200
 DDraw Ver:
 DSound Ver:
 
Product: PlantsVsZombies
 Version: 1.0.0.1051
 Time Loaded: 00:01:32
 Fullscreen: 是

**Comment by IVSpretender** [comment]
随机出现，崩溃时机并不固定。
崩溃并不频繁，刚刚过了第二关。

**Comment by IVSpretender** [comment]
能不能顺利通关不崩溃有点看运气，每次都是在刚出一批僵尸的时候崩溃的：
Exception: Access Violation (code 0xc0000005) at address 004732C0 in thread 7F24
Module: PlantsVsZombies.exe
Logical Address: 0001:000722C0

0019F94C 004732C0 0001:000722C0 PlantsVsZombies.exe
Params: 00668C44 02DF09A0 00000000 00000002


EAX:0AA93058 EBX:00000000 ECX:D8370000 EDX:02DD0C40 ESI:00000000 EDI:00000008
EIP:004732C0 ESP:0019F950  EBP:1BEA53E4
CS:0023 SS:002B DS:002B ES:002B FS:0053 GS:002B
Flags:00010246

Windows Ver: NT 6.2  Build 9200
DDraw Ver: 
DSound Ver: 

Product: PlantsVsZombies
Version: 1.0.0.1051
Time Loaded: 00:02:30
Fullscreen: 是

**Comment by IVSpretender** [comment]
在v0.06-Beta中已修复
